### ISSUE TITLE
Implementation for Pytorch

### ISSUE THREAD

**Issue by yuvaramsingh94** [marl/autopool#5]
Hi Justin,
       i like to try this for a SED work. i am looking to Implementation this on pytorch. i like to know if there exist any pytorch Implementation  . 
thanks
yuvaram

**Comment by justinsalamon** [comment]
@yuvaramsingh94 we haven't gotten round to porting this pyrtorch yet, but a PR would be most welcome!

**Comment by yuvaramsingh94** [comment]
Thanks @justinsalamon  i will work on implementing it on pytorch and raise a PR .
