### ISSUE TITLE
Explanation on the call function 

### ISSUE THREAD

**Issue by yuvaramsingh94** [marl/autopool#6]
Hi ,
   i am trying to understand the implementation by comparing it with the paper. currently i am not able to understand a particular code
```
def call(self, x, mask=None):
        scaled = self.kernel * x
        max_val = K.max(scaled, axis=self.axis, keepdims=True)
        softmax = K.exp(scaled - max_val)
        weights = softmax / K.sum(softmax, axis=self.axis, keepdims=True)
        return K.sum(x * weights, axis=self.axis, keepdims=False)
```
in this call function, we are subtracting max value from scaled ``` softmax = K.exp(scaled - max_val)```. but , i am not able to find this part on the paper . pls explain.

**Comment by bmcfee** [comment]
This is a standard trick for improving numerical stability of the soft max operation and preventing numerical underflow due to floating point operations.  See, eg, https://timvieira.github.io/blog/post/2014/02/11/exp-normalize-trick/ (edited for a better reference)
