### ISSUE TITLE
Evaluation

### ISSUE THREAD

**Issue by yuvaramsingh94** [marl/autopool#7]
Hi @justinsalamon 
    i have a doubt regarding the evaluation implementation . during evaluation(testing) do we remove the aggregator layer to get instance level tagging. in that case the Alpha of the adaptive pooling layer is used only for training, pls clarify.

thanks
yuvaram

**Comment by justinsalamon** [comment]
It depends if you're evaluating at the clip (bag) level or at the frame (instance) level. At the clip level you apply autopool with the learned per-class alpha. At the instance level you don't apply autopooling to the instance-level predictions, which are used for evaluation directly.

**Comment by yuvaramsingh94** [comment]
Thanks
